runtime: nodejs14
instance_class: F1

handlers:
  - url: /(.*\.(png|ico|jpg|json|js|svg))$
    static_files: dist/\1
    upload: dist/.*\.(png|ico|jpg|json|js|svg)$
    secure: always

  - url: .*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
